name: Basic Workflow

# Allow the workflow to be triggered manually.
on:
  - workflow_dispatch
  - push

jobs:
  basic:
    # As mentioned, a job runs on a Runner
    # Hence we now have to define that Runner
    # For more info search for "github runners"
    runs-on: ubuntu-latest

    steps:
      - name: print greeting
        run: echo "Hello workflow!"
      - name: Fail step
        run: cd matan_levy_folder_doesnt_exist
