name: Basic Workflow

# Allow the workflow to be triggered manually.
on:
  - workflow_dispatch
  - push

jobs:

  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "${{ toJSON(github) }}"

