name: Basic Workflow

# Allow the workflow to be triggered manually.
on:
  - workflow_dispatch
  - push

jobs:
  basic:
    # As mentioned, a job runs on a Runner
    # Hence we now have to define that Runner
    # For more info search for "github runners"
    runs-on: ubuntu-latest

    steps:
      - name: print greeting
        run: echo "Hello workflow!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step of second-job
        run: |
          echo "First step of second-job"
      - name: Second step of second-job
        run: |
          echo "Second step of second-job"
