# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths:
    - 'src/**'
    - 'test/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CMAKE_IS_INSTALLED: 'false'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: lcov installation
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lcov

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

      # - name: Update submodule [ gtest ]
      #   run: |
      #     cd lib/googletest
      #     git submodule update --init
      #     cd ../..

      - name: Check cmake version
        continue-on-error: true
        run: |
          if cmake --version
          then
            echo "CMAKE_IS_INSTALLED='true'" >> $GITHUB_ENV
            echo "CMake is installed"
          fi

      # - name: Print Job context
      #   env:
      #     JOB_CONTEXT: ${{toJSON(job)}}
      #   run: |
      #     echo "Job context: $JOB_CONTEXT"

      - name: actions-setup-cmake
        if: ${{ env.CMAKE_IS_INSTALLED == 'false' }}
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.17.4'


      # Runs a set of commands using the runners shell
      - name: Run cmake
        run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug

      # Runs a set of commands using the runners shell
      - name: Run make
        run: |
          cd build
          make

      # Runs a set of commands using the runners shell
      - name: Run Tests
        run: |
          cd build
          ctest

      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
